CREATE TABLE test_table (test_id INT, test_column VARCHAR, PRIMARY KEY (test_id));
CREATE TABLE "owner" (
                         "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         "name" varchar,
                         "cnp" varchar,
                         "phone_number" integer,
                         "email" varchar,
                         "created_at" timestamp,
                         "updated_at" timestamp
);

CREATE TABLE "pet" (
                       "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       "name" varchar,
                       "breed" varchar,
                       "birth_date" varchar,
                       "created_at" timestamp,
                       "updated_at" timestamp
);

CREATE TABLE "appointment" (
                               "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               "pet_id" integer,
                               "customer_details" text,
                               "datetime" date,
                               "estimated_minutes" integer,
                               "vet_details" varchar,
                               "vet_id" integer,
                               "created_at" timestamp,
                               "updated_at" timestamp
);

CREATE TABLE "invoice" (
                           "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           "cost" integer,
                           "payment_method" varchar,
                           "created_at" timestamp,
                           "updated_at" timestamp
);

CREATE TABLE "service" (
                           "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           "type" varchar,
                           "price" integer,
                           "created_at" timestamp,
                           "updated_at" timestamp
);

CREATE TABLE "veterinary" (
                              "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              "name" varchar
);

COMMENT ON COLUMN "appointment"."customer_details" IS 'Content of the post';

ALTER TABLE "pet" ADD FOREIGN KEY ("id") REFERENCES "owner" ("id");

ALTER TABLE "appointment" ADD FOREIGN KEY ("pet_id") REFERENCES "pet" ("id");

ALTER TABLE "invoice" ADD FOREIGN KEY ("id") REFERENCES "appointment" ("id");

ALTER TABLE "service" ADD FOREIGN KEY ("id") REFERENCES "appointment" ("id");

ALTER TABLE "appointment" ADD FOREIGN KEY ("id") REFERENCES "veterinary" ("id");

DROP TABLE "test_table";
